// Rewrite the instructions in your own words
/**
 * Creare un programma che chiede all'utilizatore la sua mail 
 * E virificare se la mail è valida o no 
 * */
// Write the objectives and the tests
/**
 * Creare una variabile email che contiene la mail dell'utilizatore
 * Verificare se la variabile mail inizia da una lettera o parola 
 * Verificare che la lettera che segue sia una @ seguito da una parola
 * verificare che doppo la parola che segui la @, abbiamo un . seguito da una parola
 */
// Write the pseudocode



// paste your JS generated by blockly below here

var e_mail, firstWord, numberMail, numberMail2, numberMail3, numberMail4;


e_mail = window.prompt('Scrivere la sua mail');
firstWord = e_mail.slice(0, e_mail.indexOf('@') + 1);
if (firstWord.length > 1) {
  numberMail = e_mail.indexOf('@') + 1;
  numberMail2 = e_mail.indexOf('.') + 1;
  if (numberMail2 - numberMail > 1) {
    numberMail3 = e_mail.indexOf('.') + 1;
    numberMail4 = e_mail.slice((numberMail3 - 1), e_mail.length);
    if (numberMail4.length > 2) {
      window.alert('La mail è valide');
    }
    if (numberMail4.length <= 2) {
      window.alert('La sua mail non è valida');
    }
  }
  if (numberMail2 - numberMail <= 1) {
    window.alert('La sua mail non è valida');
  }
}
if (firstWord.length <= 1) {
  window.alert('La sua mail non è valida');
}